export const users = [
  {
    id: 1,
    name: "Carlos Mendes",
    email: "carlos.mendes@escola.edu.br",
    phone: "(11) 98765-4321",
    course: "Ciência da Computação",
    role: "Professor",
    status: "Ativo",
  },
  {
    id: 2,
    name: "Beatriz Souza",
    email: "beatriz.souza@escola.edu.br",
    phone: "(11) 98776-5432",
    course: "Design Gráfico",
    role: "Professor",
    status: "Ativo",
  },
  {
    id: 3,
    name: "Ana Lima",
    email: "ana.lima@escola.edu.br",
    phone: "(11) 97654-3210",
    course: "Sistemas de Informação",
    role: "Tutor",
    status: "Ativo",
  },
  {
    id: 4,
    name: "Rafael Costa",
    email: "rafael.costa@escola.edu.br",
    phone: "(11) 96543-2109",
    course: "Design Digital",
    role: "Tutor",
    status: "Ativo",
  },
  {
    id: 5,
    name: "Marina Oliveira",
    email: "marina.oliveira@escola.edu.br",
    phone: "(11) 9432-1098",
    course: "Análise de Sistemas",
    role: "Aluno",
    status: "Ativo",
  },
  {
    id: 6,
    name: "Pedro Alves",
    email: "pedro.alves@escola.edu.br",
    phone: "(11) 94321-0987",
    course: "Engenharia de Software",
    role: "Aluno",
    status: "Ativo",
  },
  {
    id: 7,
    name: "Fernanda Lopes",
    email: "fernanda.lopes@escola.edu.br",
    phone: "(11) 93210-9876",
    course: "Ciência de Dados",
    role: "Aluno",
    status: "Inativo",
  },
  {
    id: 8,
    name: "Administrador",
    email: "admin@escola.edu.br",
    phone: "(11) 9111-2222",
    course: "-",
    role: "Administrador",
    status: "Ativo",
  },
];
export const workshops = [
  {
    id: 1,
    name: "Introdução ao Python",
    theme: "Programação",
    description: "Oficina introdutória sobre lógica de programação com Python.",
    teacher: "Carlos Mendes",
    tutor: "Ana Lima",
    date: "2026-05-12",
    time: "14:00 - 17:00",
    location: "Lab. Informática A",
    maxStudents: 30,
    enrolled: 24,
    status: "Ativa",
  },
  {
    id: 2,
    name: "Design UX/UI",
    theme: "Design",
    description: "Conceitos básicos de UX e UI aplicados a produtos digitais.",
    teacher: "Beatriz Souza",
    tutor: "Rafael Costa",
    date: "2026-05-15",
    time: "09:00 - 12:00",
    location: "Sala de Design",
    maxStudents: 20,
    enrolled: 20,
    status: "Ativa",
  },
  {
    id: 3,
    name: "Robótica Educacional",
    theme: "Tecnologia",
    description: "Introdução ao uso de robótica em atividades educacionais.",
    teacher: "Henrique Alves",
    tutor: "Ana Lima",
    date: "2026-05-20",
    time: "13:00 - 16:00",
    location: "Lab. Maker",
    maxStudents: 15,
    enrolled: 9,
    status: "Planejada",
  },
  {
    id: 4,
    name: "Fotografia Básica",
    theme: "Arte",
    description: "Fundamentos de fotografia, composição e iluminação.",
    teacher: "Márcia Ferreira",
    tutor: "Rafael Costa",
    date: "2026-04-30",
    time: "10:00 - 13:00",
    location: "Estúdio B",
    maxStudents: 12,
    enrolled: 12,
    status: "Encerrada",
  },
  {
    id: 5,
    name: "Empreendedorismo",
    theme: "Negócios",
    description: "Conceitos iniciais para criação de pequenos negócios.",
    teacher: "Rodrigo Nunes",
    tutor: "Ana Lima",
    date: "2026-05-28",
    time: "15:00 - 18:00",
    location: "Auditório Central",
    maxStudents: 50,
    enrolled: 31,
    status: "Planejada",
  },
];
export const attendance = [
  { id: 1, workshopId: 1, student: "Marina Oliveira", present: true },
  { id: 2, workshopId: 1, student: "Pedro Alves", present: true },
  { id: 3, workshopId: 1, student: "Fernanda Lopes", present: false },
  { id: 4, workshopId: 1, student: "Gabriel Santos", present: true },
  { id: 5, workshopId: 1, student: "Isabela Carmo", present: false },
  { id: 6, workshopId: 1, student: "Thiago Ramos", present: true },
  { id: 7, workshopId: 1, student: "Larissa Melo", present: true },
  { id: 8, workshopId: 1, student: "Diego Ferreira", present: false },
];
